### ISSUE TITLE
Error when running "react-scripts start"

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#1005]
**Bug Description**
When running `npm run start`, the following error occurs:

```
appTsConfig.compilerOptions[option] = value;
                                          ^

TypeError: Cannot assign to read only property 'jsx' of object '#<Object>'
    at verifyTypeScriptSetup (/Users/jamespang/Desktop/Projects/Website-1/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:239:43)
    at Object.<anonymous> (/Users/jamespang/Desktop/Projects/Website-1/node_modules/react-scripts/scripts/start.js:31:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**Steps to Reproduce**
1. Run `npm run start`
2. View the error

**Expected behavior**
No error and able to launch localhost.

**Actual behavior**
Error occurred

**Screenshots/Recordings**
<img width="1047" alt="Screen Shot 2020-11-23 at 6 54 11 PM" src="https://user-images.githubusercontent.com/32864116/99954437-b2658a80-2dbd-11eb-93d7-275b1cdb5249.png">

**OS and Browser**
 - OS: MacOS, Chrome

**Additional context**
Note that this will occur if new contributors clone our project and run npm install. Or existing contributors re-install npm packages
Seems like a recent issue with the recent create react app: https://github.com/facebook/create-react-app/issues/10112
Workaround: https://github.com/facebook/create-react-app/issues/9868#issuecomment-723576740

**Account Number**
Acc No: c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

**Comment by thesanjeevsharma** [comment]
@jamessspanggg I am gonna close this. While reviewing a PR yesterday, I updated react-scripts to 4.0.1.
