### ISSUE TITLE
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1830]
If you go to the `/project-rules/overview` page and refresh, you will see this error:

<img width="501" alt="Screen Shot 2021-05-29 at 6 45 59 PM" src="https://user-images.githubusercontent.com/8547538/120089345-23a83200-c0ae-11eb-802d-8a3986c46893.png">

```
index.js:1 Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:5075:24
    at a
    at A (http://localhost:3000/static/js/main.chunk.js:3624:3)
    at p
    at DocSubSection (http://localhost:3000/static/js/main.chunk.js:8025:3)
    at section
    at DocContainer (http://localhost:3000/static/js/main.chunk.js:6641:3)
    at ProjectsOverview
    at div
    at div
    at DashboardLayout (http://localhost:3000/static/js/main.chunk.js:6096:3)
    at Projects (http://localhost:3000/static/js/main.chunk.js:54994:73)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:147329:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:147531:29)
    at div
    at div
    at Layout (http://localhost:3000/static/js/main.chunk.js:14242:3)
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:146964:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:146584:35)
    at App
    at r (http://localhost:3000/static/js/vendors~main.chunk.js:136791:19)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:144200:20)
```

**Comment by guptstagram** [comment]
@jamessspanggg @buckyroberts  Can I take this?

**Comment by jamessspanggg** [comment]
> @jamessspanggg @buckyroberts Can I take this?

sure go ahead

**Comment by bitch-ctrl** [comment]
Is it done or Should i take this one?

**Comment by guptstagram** [comment]
This is causing issue because the Icon Component in ui-js is using div for wrapping the Icon Component.

I have changed the wrapper from div to span and raised PR.

https://github.com/thenewboston-developers/ui-js/pull/20

**Comment by Carl256** [comment]
still open? I think I can be of help here.

**Comment by angle943** [comment]
no longer an issue
